server:
  port: 9910
spring:
  application:
    name: zuuldemo
zuul:
  prefix: /api
#  routes:
#    service: /service/** #zuul拦截的路径
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9900/eureka
#    registry-fetch-interval-seconds: 5
#  instance:
#    prefer-ip-address: true #是否注册ip地址
#    ip-address: 127.0.0.1 #注册的IP地址
